// Copyright 2017-2021 @polkadot/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @tetcoin/dev, do not edit

export const packageInfo = { name: '@tetcoin/wasm-crypto-wasm', version: '3.2.3' };
